java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    em-npa:
      secrets:
        - microservicekey-em-npa-app
  environment:
    ENABLE_LIQUIBASE: true
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/postgres?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    CCD_DATA_API_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
    CCD_DATA_API: http://ccd-data-store-api-aat.service.core-compute-aat.internal

  postgresql:
    enabled: true
