postgresql:
#  initdbScripts:
#    init.sql: |-
#      CREATE USER emnpa WITH PASSWORD 'emnpa';
#      CREATE DATABASE emnpa WITH OWNER = emnpa ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: emnpa
  postgresqlPassword: emnpa
  postgresqlDatabase: emnpa
  nameOverride: rpa-native-pdf-annotator-db
  persistence:
    enabled: false
  tags:
    postgresql-pod: true

npa-app:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 8080
  readinessDelay: 20
  readinessTimeout: 20
  readinessFailureThreshold: 7
  readinessPeriod: 15
  livenessDelay: 20
  livenessTimeout: 20
  livenessPeriod: 15
  livenessFailureThreshold: 7
  keyVaults:
    rpa:
      resourceGroup: rpa
      secrets:
        - AppInsightsInstrumentationKey
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-em-npa-app
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://${SERVICE_NAME}-rpa-native-pdf-annotator-db:5432/emnpa?ssl=disable
    SPRING_DATASOURCE_USERNAME: emnpa
    SPRING_DATASOURCE_PASSWORD: emnpa

    ENABLE_DB_MIGRATE: true
    REFORM_SERVICE_NAME: em-npa
    REFORM_TEAM: evidence
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    PACKAGES_NAME: em-npa
    PACKAGES_PROJECT: evidence
    PACKAGES_ENVIRONMENT: preview
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    SHOW_SQL: true
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    S2S_NAMES_WHITELIST: em_api,em_gw,ccd_gw,ccd_data,sscs,divorce_document_upload,divorce_document_generator,probate_backend,jui_webapp,pui_webapp
    CASE_WORKER_ROLES: caseworker-probate,caseworker-cmc,caseworker-sscs,caseworker-divorce
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    ENABLE_LIQUIBASE: true
    SERVER_PORT: 8080
